const testimonies = [
  "Tunay na budget-friendly, kaya kampante akong bumalik. Tiwala ako sa kanilang serbisyo. - Maria Santos",
  "Sobrang sulit dito, at talagang maaasahan ang gamutan. Dito na ako palagi. - Sofia Reyes",
  "Presyo ay pang-masa, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Isabella Garcia",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Andrea Cruz",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Legit na legit! - Samantha Lim",
  "Tunay na budget-friendly, kaya sulit bawat piso. Dito na ako palagi. - Patricia Dela Cruz",
  "Sobrang sulit dito, kaya sulit bawat piso. Highly recommended! - Gabrielle Fernandez",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Highly recommended! - Jasmine Mendoza",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Dito na ako palagi. - Angel Torres",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Christine Ramos",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Nicole Castro",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Dito na ako palagi. - Kimberly Rivera",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Michelle Gonzales",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Salamat sa klinika! - Stephanie Perez",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Danielle Santiago",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Alyssa Dela Rosa",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Erica Bautista",
  "Napakamura at maaasahan, kaya sulit bawat piso. Dito na ako palagi. - Jessica Flores",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Legit na legit! - Sarah David",
  "Talagang mura at maayos, kaya sulit bawat piso. Salamat sa klinika! - Chloe Reyes",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Highly recommended! - Olivia Santos",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Tiwala ako sa kanilang serbisyo. - Emily Garcia",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Legit na legit! - Hannah Cruz",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Tiwala ako sa kanilang serbisyo. - Grace Lim",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Highly recommended! - Victoria Dela Cruz",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Dito na ako palagi. - Sophia Fernandez",
  "Legit at affordable, kaya sulit bawat piso. Sobrang saya ko sa experience. - Ella Mendoza",
  "Napakamura at maaasahan, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Mia Torres",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Ava Ramos",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Highly recommended! - Lily Castro",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Zoe Rivera",
  "Tunay na budget-friendly, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Nora Gonzales",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Legit na legit! - Luna Perez",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Sobrang saya ko sa experience. - Stella Santiago",
  "Sobrang sulit dito, kaya sulit bawat piso. Highly recommended! - Ruby Dela Rosa",
  "Sobrang sulit dito, kaya kampante akong bumalik. Tiwala ako sa kanilang serbisyo. - Daisy Bautista",
  "Legit at affordable, kaya sulit bawat piso. Napakaganda ng serbisyo! - Violet Flores",
  "Tunay na budget-friendly, kaya sulit bawat piso. Napakaganda ng serbisyo! - Hazel David",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Willow Reyes",
  "Legit at affordable, kaya sulit bawat piso. Salamat sa klinika! - Aurora Santos",
  "Abot-kaya ang presyo, at napaka-professional ng mga doktor. Salamat sa klinika! - Clara Garcia",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Salamat sa klinika! - Evelyn Cruz",
  "Sobrang sulit dito, kaya sulit bawat piso. Dito na ako palagi. - Grace Lim",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Ivy Dela Cruz",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - June Fernandez",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Napakaganda ng serbisyo! - Kate Mendoza",
  "Sobrang sulit dito, at talagang maaasahan ang gamutan. Dito na ako palagi. - Lucy Torres",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Maya Ramos",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Babalik ulit ako dito. - Nina Castro",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Dito na ako palagi. - Olive Rivera",
  "Presyo ay pang-masa, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Paige Gonzales",
  "Legit at affordable, kaya sulit bawat piso. Legit na legit! - Quinn Perez",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Dito na ako palagi. - Rose Santiago",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Dito na ako palagi. - Sage Dela Rosa",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Tess Bautista",
  "Tunay na budget-friendly, kaya sulit bawat piso. Dito na ako palagi. - Uma Flores",
  "Talagang mura at maayos, kaya sulit bawat piso. Napakaganda ng serbisyo! - Vera David",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Wendy Reyes",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Xena Santos",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Dito na ako palagi. - Yara Garcia",
  "Sobrang sulit dito, kaya sulit bawat piso. Dito na ako palagi. - Zara Cruz",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Abby Lim",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Bella Dela Cruz",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Legit na legit! - Cara Fernandez",
  "Legit at affordable, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Dana Mendoza",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Legit na legit! - Eden Torres",
  "Talagang mura at maayos, kaya sulit bawat piso. Legit na legit! - Faith Ramos",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Gia Castro",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Salamat sa klinika! - Hope Rivera",
  "Napakamura at maaasahan, kaya hindi nakaka-stress sa bulsa. Legit na legit! - Iris Gonzales",
  "Talagang mura at maayos, kaya sulit bawat piso. Legit na legit! - Jade Perez",
  "Abot-kaya ang presyo, pero hindi tinipid ang serbisyo. Legit na legit! - Kyla Santiago",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Lana Dela Rosa",
  "Tunay na budget-friendly, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Mara Bautista",
  "Tunay na budget-friendly, kaya sulit bawat piso. Dito na ako palagi. - Nala Flores",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Highly recommended! - Opal David",
  "Legit at affordable, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Pia Reyes",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Rhea Santos",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Skye Garcia",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Highly recommended! - Tara Cruz",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Legit na legit! - Una Lim",
  "Napakamura at maaasahan, kaya sulit bawat piso. Dito na ako palagi. - Vina Dela Cruz",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Legit na legit! - Wren Fernandez",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Yumi Mendoza",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Dito na ako palagi. - Zuri Torres",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Anya Ramos",
  "Talagang mura at maayos, kaya kampante akong bumalik. Highly recommended! - Bree Castro",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Cora Rivera",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Legit na legit! - Demi Gonzales",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Eden Perez",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Fawn Santiago",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Dito na ako palagi. - Gwen Dela Rosa",
  "Napakamura at maaasahan, pero hindi tinipid ang serbisyo. Tiwala ako sa kanilang serbisyo. - Holly Bautista",
  "Tunay na budget-friendly, na may kalidad pa rin ang serbisyo. Legit na legit! - Iris Flores",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - June David",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Legit na legit! - Kiki Reyes",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Lola Santos",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Mimi Garcia",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Nala Cruz",
  "Napakamura at maaasahan, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Opal Lim",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Piper Dela Cruz",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Salamat sa klinika! - Queenie Fernandez",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Legit na legit! - Rina Mendoza",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Salamat sa klinika! - Sasha Torres",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Trixie Ramos",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Sobrang saya ko sa experience. - Uma Castro",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Veda Rivera",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Legit na legit! - Wendy Gonzales",
  "Tunay na budget-friendly, pero hindi tinipid ang serbisyo. Legit na legit! - Xenia Perez",
  "Tunay na budget-friendly, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Yana Santiago",
  "Talagang mura at maayos, pero hindi tinipid ang serbisyo. Legit na legit! - Zola Dela Rosa",
  "Tunay na budget-friendly, kaya sulit bawat piso. Dito na ako palagi. - Aaliyah Bautista",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Babalik ulit ako dito. - Bianca Flores",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Tiwala ako sa kanilang serbisyo. - Carla David",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Salamat sa klinika! - Dina Reyes",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Elara Santos",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Dito na ako palagi. - Freya Garcia",
  "Abot-kaya ang presyo, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Giselle Cruz",
  "Abot-kaya ang presyo, pero hindi tinipid ang serbisyo. Legit na legit! - Heidi Lim",
  "Tunay na budget-friendly, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Ines Dela Cruz",
  "Legit at affordable, kaya kampante akong bumalik. Babalik ulit ako dito. - Jessa Fernandez",
  "Presyo ay pang-masa, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Kiana Mendoza",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Lena Torres",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Dito na ako palagi. - Mila Ramos",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Salamat sa klinika! - Naya Castro",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Dito na ako palagi. - Orla Rivera",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Napakaganda ng serbisyo! - Petra Gonzales",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Raya Perez",
  "Legit at affordable, kaya sulit bawat piso. Babalik ulit ako dito. - Siena Santiago",
  "Legit at affordable, at napaka-professional ng mga doktor. Legit na legit! - Talia Dela Rosa",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Napakaganda ng serbisyo! - Uma Bautista",
  "Talagang mura at maayos, kaya sulit bawat piso. Highly recommended! - Vada Flores",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Wren David",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Dito na ako palagi. - Xyla Reyes",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Yael Santos",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Zola Garcia",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Aira Cruz",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Babalik ulit ako dito. - Bea Lim",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Cami Dela Cruz",
  "Napakamura at maaasahan, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Dara Fernandez",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Babalik ulit ako dito. - Elina Mendoza",
  "Napakamura at maaasahan, kaya sulit bawat piso. Babalik ulit ako dito. - Fina Torres",
  "Tunay na budget-friendly, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Gia Ramos",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Salamat sa klinika! - Hana Castro",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Ina Rivera",
  "Tunay na budget-friendly, kaya kampante akong bumalik. Legit na legit! - Jina Gonzales",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Highly recommended! - Kara Perez",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Highly recommended! - Lara Santiago",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Mona Dela Rosa",
  "Sobrang sulit dito, kaya sulit bawat piso. Dito na ako palagi. - Naya Bautista",
  "Legit at affordable, at laging may malasakit sa pasyente. Salamat sa klinika! - Ona Flores",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Pia David",
  "Talagang mura at maayos, kaya kampante akong bumalik. Babalik ulit ako dito. - Rina Reyes",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Sara Santos",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Highly recommended! - Tina Garcia",
  "Napakamura at maaasahan, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Ula Cruz",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Legit na legit! - Vina Lim",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Legit na legit! - Wina Dela Cruz",
  "Sobrang sulit dito, at laging may malasakit sa pasyente. Salamat sa klinika! - Xena Fernandez",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Salamat sa klinika! - Yana Mendoza",
  "Napakamura at maaasahan, at napaka-professional ng mga doktor. Salamat sa klinika! - Zina Torres",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Aida Ramos",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - Bella Castro",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Cora Rivera",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Dina Gonzales",
  "Talagang mura at maayos, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Ella Perez",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Fina Santiago",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Salamat sa klinika! - Gina Dela Rosa",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Highly recommended! - Hina Bautista",
  "Sobrang sulit dito, kaya kampante akong bumalik. Salamat sa klinika! - Ina Flores",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Jina David",
  "Presyo ay pang-masa, kaya sulit bawat piso. Sobrang saya ko sa experience. - Kina Reyes",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Lina Santos",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Mina Garcia",
  "Napakamura at maaasahan, kaya sulit bawat piso. Salamat sa klinika! - Nina Cruz",
  "Presyo ay pang-masa, kaya sulit bawat piso. Babalik ulit ako dito. - Ona Lim",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Dito na ako palagi. - Pia Dela Cruz",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Legit na legit! - Rina Fernandez",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Sara Mendoza",
  "Sobrang sulit dito, kaya kampante akong bumalik. Highly recommended! - Tina Torres",
  "Talagang mura at maayos, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Ula Ramos",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Salamat sa klinika! - Vina Castro",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Wina Rivera",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Xena Gonzales",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Salamat sa klinika! - Yana Perez",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Salamat sa klinika! - Zina Santiago",
  "Sobrang sulit dito, kaya sulit bawat piso. Tiwala ako sa kanilang serbisyo. - Aida Dela Rosa",
  "Presyo ay pang-masa, kaya hindi nakaka-stress sa bulsa. Highly recommended! - Bella Bautista",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Cora Flores",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Dina David",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Ella Reyes",
  "Abot-kaya ang presyo, at talagang maaasahan ang gamutan. Salamat sa klinika! - Fina Santos",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Gina Garcia",
  "Legit at affordable, at napaka-professional ng mga doktor. Dito na ako palagi. - Hina Cruz",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Salamat sa klinika! - Ina Lim",
  "Legit at affordable, at napaka-professional ng mga doktor. Legit na legit! - Jina Dela Cruz",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Kina Fernandez",
  "Abot-kaya ang presyo, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Lina Mendoza",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Napakaganda ng serbisyo! - Mina Torres",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Highly recommended! - Nina Ramos",
  "Legit at affordable, at laging may malasakit sa pasyente. Babalik ulit ako dito. - Ona Castro",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Highly recommended! - Pia Rivera",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Rina Gonzales",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Sara Perez",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Dito na ako palagi. - Tina Santiago",
  "Legit at affordable, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Ula Dela Rosa",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Vina Bautista",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Wina Flores",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Dito na ako palagi. - Xena David",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Yana Reyes",
  "Napakamura at maaasahan, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - Zina Santos",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Legit na legit! - Aida Garcia",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Bella Cruz",
  "Sobrang sulit dito, kaya kampante akong bumalik. Salamat sa klinika! - Cora Lim",
  "Legit at affordable, at talagang maaasahan ang gamutan. Salamat sa klinika! - Dina Dela Cruz",
  "Napakamura at maaasahan, kaya sulit bawat piso. Dito na ako palagi. - Ella Fernandez",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Fina Mendoza",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Highly recommended! - Gina Torres",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Dito na ako palagi. - Hina Ramos",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Ina Castro",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Jina Rivera",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Legit na legit! - Kina Gonzales",
  "Tunay na budget-friendly, na may kalidad pa rin ang serbisyo. Legit na legit! - Lina Perez",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Mina Santiago",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Nina Dela Rosa",
  "Presyo ay pang-masa, kaya sulit bawat piso. Dito na ako palagi. - Ona Bautista",
  "Presyo ay pang-masa, kaya sulit bawat piso. Sobrang saya ko sa experience. - Pia Flores",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Legit na legit! - Rina David",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Sara Reyes",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Highly recommended! - Tina Santos",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Ula Garcia",
  "Tunay na budget-friendly, kaya sulit bawat piso. Babalik ulit ako dito. - Vina Cruz",
  "Talagang mura at maayos, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Wina Lim",
  "Presyo ay pang-masa, at laging may malasakit sa pasyente. Legit na legit! - Xena Dela Cruz",
  "Tunay na budget-friendly, kaya sulit bawat piso. Legit na legit! - Yana Fernandez",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - Zina Mendoza",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Highly recommended! - Aaliyah Torres",
  "Abot-kaya ang presyo, kaya kampante akong bumalik. Legit na legit! - Bianca Ramos",
  "Sobrang sulit dito, kaya kampante akong bumalik. Napakaganda ng serbisyo! - Carla Castro",
  "Sobrang sulit dito, kaya sulit bawat piso. Highly recommended! - Dina Rivera",
  "Napakamura at maaasahan, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Elara Gonzales",
  "Legit at affordable, at talagang maaasahan ang gamutan. Legit na legit! - Freya Perez",
  "Napakamura at maaasahan, at napaka-professional ng mga doktor. Highly recommended! - Giselle Santiago",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Heidi Dela Rosa",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Highly recommended! - Ines Bautista",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Dito na ako palagi. - Jessa Flores",
  "Presyo ay pang-masa, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Kiana David",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Lena Reyes",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Napakaganda ng serbisyo! - Mila Santos",
  "Tunay na budget-friendly, kaya kampante akong bumalik. Salamat sa klinika! - Naya Garcia",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Tiwala ako sa kanilang serbisyo. - Orla Cruz",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Highly recommended! - Petra Lim",
  "Sobrang sulit dito, at laging may malasakit sa pasyente. Dito na ako palagi. - Raya Dela Cruz",
  "Legit at affordable, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Siena Fernandez",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Napakaganda ng serbisyo! - Talia Mendoza",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Legit na legit! - Uma Torres",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Vada Ramos",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Wren Castro",
  "Tunay na budget-friendly, kaya sulit bawat piso. Salamat sa klinika! - Xyla Rivera",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Tiwala ako sa kanilang serbisyo. - Yael Gonzales",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Zola Perez",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Aira Santiago",
  "Talagang mura at maayos, na may kalidad pa rin ang serbisyo. Highly recommended! - Bea Dela Rosa",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Cami Bautista",
  "Sobrang sulit dito, pero hindi tinipid ang serbisyo. Highly recommended! - Dara Flores",
  "Hindi ako nabigatan sa gastos, kaya sulit bawat piso. Salamat sa klinika! - Elina David",
  "Legit at affordable, kaya sulit bawat piso. Tiwala ako sa kanilang serbisyo. - Fina Reyes",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Legit na legit! - Gina Santos",
  "Napakamura at maaasahan, at napaka-professional ng mga doktor. Dito na ako palagi. - Hina Garcia",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Ina Cruz",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Jina Lim",
  "Sobrang sulit dito, kaya kampante akong bumalik. Highly recommended! - Kina Dela Cruz",
  "Tunay na budget-friendly, kaya sulit bawat piso. Babalik ulit ako dito. - Lina Fernandez",
  "Abot-kaya ang presyo, pero hindi tinipid ang serbisyo. Tiwala ako sa kanilang serbisyo. - Mimi Mendoza",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Nala Torres",
  "Talagang mura at maayos, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Opal Ramos",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Legit na legit! - Piper Castro",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Legit na legit! - Queenie Rivera",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Rina Gonzales",
  "Sobrang sulit dito, at talagang maaasahan ang gamutan. Babalik ulit ako dito. - Sara Perez",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Highly recommended! - Tina Santiago",
  "Talagang mura at maayos, kaya sulit bawat piso. Highly recommended! - Ula Dela Rosa",
  "Tunay na budget-friendly, pero hindi tinipid ang serbisyo. Dito na ako palagi. - Vina Bautista",
  "Presyo ay pang-masa, at laging may malasakit sa pasyente. Legit na legit! - Wina Flores",
  "Abot-kaya ang presyo, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Xena David",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Napakaganda ng serbisyo! - Yana Reyes",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Zina Santos",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Aaliyah Garcia",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Bianca Cruz",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Carla Lim",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Dina Dela Cruz",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Ella Fernandez",
  "Talagang mura at maayos, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Fina Mendoza",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Legit na legit! - Gina Torres",
  "Legit at affordable, at laging may malasakit sa pasyente. Babalik ulit ako dito. - Hina Ramos",
  "Abot-kaya ang presyo, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Ina Castro",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Jina Rivera",
  "Talagang mura at maayos, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Kina Gonzales",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Babalik ulit ako dito. - Lina Perez",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Mimi Santiago",
  "Legit at affordable, at talagang maaasahan ang gamutan. Salamat sa klinika! - Nala Dela Rosa",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Legit na legit! - Opal Bautista",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Tiwala ako sa kanilang serbisyo. - Piper Flores",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Queenie David",
  "Talagang mura at maayos, kaya hindi nakaka-stress sa bulsa. Legit na legit! - Rina Reyes",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Tiwala ako sa kanilang serbisyo. - Sara Santos",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Legit na legit! - Tina Garcia",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Legit na legit! - Ula Cruz",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Vina Lim",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Dito na ako palagi. - Wina Dela Cruz",
  "Talagang mura at maayos, kaya kampante akong bumalik. Legit na legit! - Xena Fernandez",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - Yana Mendoza",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Tiwala ako sa kanilang serbisyo. - Zina Torres",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Aaliyah Ramos",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Babalik ulit ako dito. - Bianca Castro",
  "Presyo ay pang-masa, at laging may malasakit sa pasyente. Dito na ako palagi. - Carla Rivera",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Dina Gonzales",
  "Legit at affordable, at napaka-professional ng mga doktor. Salamat sa klinika! - Elara Perez",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Legit na legit! - Freya Santiago",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Highly recommended! - Giselle Dela Rosa",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Salamat sa klinika! - Heidi Bautista",
  "Legit at affordable, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Ines Flores",
  "Talagang mura at maayos, kaya kampante akong bumalik. Salamat sa klinika! - Jessa David",
  "Napakamura at maaasahan, kaya sulit bawat piso. Babalik ulit ako dito. - Kiana Reyes",
  "Abot-kaya ang presyo, kaya hindi nakaka-stress sa bulsa. Babalik ulit ako dito. - Lena Santos",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Dito na ako palagi. - Mila Garcia",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Naya Cruz",
  "Sobrang sulit dito, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Orla Lim",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Legit na legit! - Petra Dela Cruz",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Dito na ako palagi. - Raya Fernandez",
  "Sobrang sulit dito, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Siena Mendoza",
  "Abot-kaya ang presyo, at talagang maaasahan ang gamutan. Salamat sa klinika! - Talia Torres",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Salamat sa klinika! - Uma Ramos",
  "Tunay na budget-friendly, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Vada Castro",
  "Sobrang sulit dito, pero hindi tinipid ang serbisyo. Tiwala ako sa kanilang serbisyo. - Wren Rivera",
  "Legit at affordable, kaya kampante akong bumalik. Highly recommended! - Xyla Gonzales",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Dito na ako palagi. - Yael Perez",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Zola Santiago",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Aira Dela Rosa",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Dito na ako palagi. - Bea Bautista",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Cami Flores",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Dara David",
  "Legit at affordable, at napaka-professional ng mga doktor. Highly recommended! - Elina Reyes",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Fina Santos",
  "Napakamura at maaasahan, kaya sulit bawat piso. Salamat sa klinika! - Gina Garcia",
  "Tunay na budget-friendly, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Hina Cruz",
  "Abot-kaya ang presyo, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Ina Lim",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Dito na ako palagi. - Jina Dela Cruz",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Kina Fernandez",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - Lina Mendoza",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Legit na legit! - Mimi Torres",
  "Tunay na budget-friendly, kaya sulit bawat piso. Salamat sa klinika! - Nala Ramos",
  "Napakamura at maaasahan, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Opal Castro",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Piper Rivera",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Babalik ulit ako dito. - Queenie Gonzales",
  "Legit at affordable, kaya kampante akong bumalik. Dito na ako palagi. - Rina Perez",
  "Legit at affordable, kaya sulit bawat piso. Dito na ako palagi. - Sara Santiago",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Highly recommended! - Tina Dela Rosa",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Salamat sa klinika! - Ula Bautista",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Dito na ako palagi. - Vina Flores",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Babalik ulit ako dito. - Wina David",
  "Legit at affordable, kaya kampante akong bumalik. Highly recommended! - Xena Reyes",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Legit na legit! - Yael Santos",
  "Legit at affordable, at napaka-professional ng mga doktor. Salamat sa klinika! - Zola Garcia",
  "Sobrang sulit dito, at laging may malasakit sa pasyente. Highly recommended! - Aira Cruz",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Bea Lim",
  "Sobrang sulit dito, kaya kampante akong bumalik. Salamat sa klinika! - Cami Dela Cruz",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Dara Fernandez",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Elina Mendoza",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Fina Torres",
  "Presyo ay pang-masa, at laging may malasakit sa pasyente. Highly recommended! - Gina Ramos",
  "Abot-kaya ang presyo, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Hana Castro",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Tiwala ako sa kanilang serbisyo. - Ina Rivera",
  "Presyo ay pang-masa, kaya sulit bawat piso. Babalik ulit ako dito. - Jina Gonzales",
  "Talagang mura at maayos, kaya sulit bawat piso. Dito na ako palagi. - Kina Perez",
  "Talagang mura at maayos, kaya kampante akong bumalik. Highly recommended! - Lina Santiago",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Legit na legit! - Mimi Dela Rosa",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Nala Bautista",
  "Talagang mura at maayos, kaya sulit bawat piso. Dito na ako palagi. - Opal Flores",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Dito na ako palagi. - Piper David",
  "Sobrang sulit dito, at talagang maaasahan ang gamutan. Dito na ako palagi. - Queenie Reyes",
  "Napakamura at maaasahan, pero hindi tinipid ang serbisyo. Highly recommended! - Rina Santos",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Sara Garcia",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Tina Cruz",
  "Legit at affordable, at talagang maaasahan ang gamutan. Highly recommended! - Ula Lim",
  "Sobrang sulit dito, kaya sulit bawat piso. Napakaganda ng serbisyo! - Vina Dela Cruz",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Tiwala ako sa kanilang serbisyo. - Wina Fernandez",
  "Tunay na budget-friendly, na may kalidad pa rin ang serbisyo. Sobrang saya ko sa experience. - Xena Mendoza",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Tiwala ako sa kanilang serbisyo. - Yana Torres",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Highly recommended! - Zina Ramos",
  "Tunay na budget-friendly, na may kalidad pa rin ang serbisyo. Legit na legit! - Aida Castro",
  "Sobrang sulit dito, kaya sulit bawat piso. Dito na ako palagi. - Bella Rivera",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Legit na legit! - Cora Gonzales",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Sobrang saya ko sa experience. - Dina Perez",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Highly recommended! - Ella Santiago",
  "Sobrang sulit dito, kaya sulit bawat piso. Sobrang saya ko sa experience. - Fina Dela Rosa",
  "Hindi ako nabigatan sa gastos, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Gina Bautista",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Salamat sa klinika! - Hina Flores",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Ina David",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Jina Reyes",
  "Tunay na budget-friendly, na may kalidad pa rin ang serbisyo. Salamat sa klinika! - Kina Santos",
  "Napakamura at maaasahan, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Lina Garcia",
  "Napakamura at maaasahan, kaya sulit bawat piso. Salamat sa klinika! - Mimi Cruz",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Nala Lim",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Legit na legit! - Opal Dela Cruz",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Dito na ako palagi. - Piper Fernandez",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Tiwala ako sa kanilang serbisyo. - Queenie Mendoza",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Rina Torres",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Sara Ramos",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Salamat sa klinika! - Tina Castro",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Napakaganda ng serbisyo! - Ula Rivera",
  "Sobrang sulit dito, kaya sulit bawat piso. Napakaganda ng serbisyo! - Vina Gonzales",
  "Sobrang sulit dito, kaya kampante akong bumalik. Legit na legit! - Wina Perez",
  "Legit at affordable, at napaka-professional ng mga doktor. Dito na ako palagi. - Xena Santiago",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Dito na ako palagi. - Yana Dela Rosa",
  "Legit at affordable, kaya kampante akong bumalik. Highly recommended! - Zina Bautista",
  "Napakamura at maaasahan, kaya sulit bawat piso. Napakaganda ng serbisyo! - Aaliyah Flores",
  "Presyo ay pang-masa, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Bianca David",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Salamat sa klinika! - Carla Reyes",
  "Legit at affordable, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Dina Santos",
  "Napakamura at maaasahan, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Elara Garcia",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Legit na legit! - Freya Cruz",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Sobrang saya ko sa experience. - Giselle Lim",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Salamat sa klinika! - Heidi Dela Cruz",
  "Talagang mura at maayos, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Ines Fernandez",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Jessa Mendoza",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Kiana Torres",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Lena Ramos",
  "Presyo ay pang-masa, kaya hindi nakaka-stress sa bulsa. Legit na legit! - Mila Castro",
  "Talagang mura at maayos, at talagang maaasahan ang gamutan. Salamat sa klinika! - Naya Rivera",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Orla Gonzales",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Napakaganda ng serbisyo! - Petra Perez",
  "Napakamura at maaasahan, pero hindi tinipid ang serbisyo. Sobrang saya ko sa experience. - Raya Santiago",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Legit na legit! - Siena Dela Rosa",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Tiwala ako sa kanilang serbisyo. - Talia Bautista",
  "Sobrang sulit dito, at laging may malasakit sa pasyente. Tiwala ako sa kanilang serbisyo. - Uma Flores",
  "Legit at affordable, at talagang maaasahan ang gamutan. Babalik ulit ako dito. - Vada David",
  "Tunay na budget-friendly, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Wren Reyes",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Salamat sa klinika! - Xena Santos",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Tiwala ako sa kanilang serbisyo. - Yael Garcia",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Zola Cruz",
  "Tunay na budget-friendly, at talagang maaasahan ang gamutan. Dito na ako palagi. - Aira Lim",
  "Hindi ako nabigatan sa gastos, at laging may malasakit sa pasyente. Legit na legit! - Bea Dela Cruz",
  "Legit at affordable, kaya sulit bawat piso. Salamat sa klinika! - Cami Fernandez",
  "Sobrang sulit dito, kaya hindi nakaka-stress sa bulsa. Salamat sa klinika! - Dara Mendoza",
  "Abot-kaya ang presyo, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Elina Torres",
  "Sobrang sulit dito, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Fina Ramos",
  "Legit at affordable, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Gina Castro",
  "Sobrang sulit dito, kaya sulit bawat piso. Legit na legit! - Hina Rivera",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Ina Gonzales",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Jina Perez",
  "Abot-kaya ang presyo, at napaka-professional ng mga doktor. Salamat sa klinika! - Kina Santiago",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Highly recommended! - Lina Dela Rosa",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Napakaganda ng serbisyo! - Mimi Bautista",
  "Talagang mura at maayos, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Nala Flores",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Opal David",
  "Legit at affordable, kaya hindi nakaka-stress sa bulsa. Sobrang saya ko sa experience. - Piper Reyes",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Dito na ako palagi. - Queenie Santos",
  "Hindi ako nabigatan sa gastos, kaya hindi nakaka-stress sa bulsa. Napakaganda ng serbisyo! - Rina Garcia",
  "Legit at affordable, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Sara Cruz",
  "Hindi ako nabigatan sa gastos, at talagang maaasahan ang gamutan. Salamat sa klinika! - Tina Lim",
  "Abot-kaya ang presyo, at talagang maaasahan ang gamutan. Legit na legit! - Ula Dela Cruz",
  "Presyo ay pang-masa, pero hindi tinipid ang serbisyo. Legit na legit! - Vina Fernandez",
  "Legit at affordable, at talagang maaasahan ang gamutan. Sobrang saya ko sa experience. - Wina Mendoza",
  "Legit at affordable, kaya kampante akong bumalik. Sobrang saya ko sa experience. - Xena Torres",
  "Abot-kaya ang presyo, kaya sulit bawat piso. Highly recommended! - Yana Ramos",
  "Tunay na budget-friendly, kaya hindi nakaka-stress sa bulsa. Salamat sa klinika! - Zina Castro",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Salamat sa klinika! - Aaliyah Rivera",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Bianca Gonzales",
  "Tunay na budget-friendly, at laging may malasakit sa pasyente. Babalik ulit ako dito. - Carla Perez",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Sobrang saya ko sa experience. - Dina Santiago",
  "Abot-kaya ang presyo, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Elara Dela Rosa",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Dito na ako palagi. - Freya Bautista",
  "Presyo ay pang-masa, at napaka-professional ng mga doktor. Tiwala ako sa kanilang serbisyo. - Giselle Flores",
  "Tunay na budget-friendly, kaya kampante akong bumalik. Dito na ako palagi. - Heidi David",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Dito na ako palagi. - Ines Reyes",
  "Napakamura at maaasahan, at napaka-professional ng mga doktor. Salamat sa klinika! - Jessa Santos",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Kiana Garcia",
  "Presyo ay pang-masa, kaya sulit bawat piso. Tiwala ako sa kanilang serbisyo. - Lena Cruz",
  "Abot-kaya ang presyo, kaya kampante akong bumalik. Salamat sa klinika! - Mila Lim",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Tiwala ako sa kanilang serbisyo. - Naya Dela Cruz",
  "Hindi ako nabigatan sa gastos, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Orla Fernandez",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Tiwala ako sa kanilang serbisyo. - Petra Mendoza",
  "Hindi ako nabigatan sa gastos, at napaka-professional ng mga doktor. Napakaganda ng serbisyo! - Raya Torres",
  "Abot-kaya ang presyo, at laging may malasakit sa pasyente. Tiwala ako sa kanilang serbisyo. - Siena Ramos",
  "Sobrang sulit dito, at napaka-professional ng mga doktor. Babalik ulit ako dito. - Talia Castro",
  "Hindi ako nabigatan sa gastos, kaya kampante akong bumalik. Highly recommended! - Uma Rivera",
  "Talagang mura at maayos, at napaka-professional ng mga doktor. Sobrang saya ko sa experience. - Vada Gonzales",
  "Napakamura at maaasahan, at talagang maaasahan ang gamutan. Salamat sa klinika! - Wren Perez",
  "Presyo ay pang-masa, at talagang maaasahan ang gamutan. Napakaganda ng serbisyo! - Xena Santiago",
  "Tunay na budget-friendly, kaya sulit bawat piso. Highly recommended! - Yana Dela Rosa",
  "Talagang mura at maayos, pero hindi tinipid ang serbisyo. Babalik ulit ako dito. - Zina Bautista",
  "Napakamura at maaasahan, kaya kampante akong bumalik. Highly recommended! - Aaliyah Flores",
  "Talagang mura at maayos, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Bianca David",
  "Sobrang sulit dito, pero hindi tinipid ang serbisyo. Tiwala ako sa kanilang serbisyo. - Carla Reyes",
  "Abot-kaya ang presyo, pero hindi tinipid ang serbisyo. Salamat sa klinika! - Dina Santos",
  "Presyo ay pang-masa, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Elara Garcia",
  "Napakamura at maaasahan, at laging may malasakit sa pasyente. Sobrang saya ko sa experience. - Freya Cruz",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Napakaganda ng serbisyo! - Giselle Lim",
  "Abot-kaya ang presyo, na may kalidad pa rin ang serbisyo. Babalik ulit ako dito. - Heidi Dela Cruz"
];
